### ISSUE TITLE
DVI not working

### ISSUE THREAD

**Issue by pogossian** [DmitriyyyyS/Asus-Prime-H310M-R#1]
Hi, did you try DVI port ? For me, working only HDMI, I need dual monitor

**Comment by DmitriyyyyS** [comment]
multimonitoring on intel graphics does not work, you need a discrete graphics card.

**Comment by pogossian** [comment]
but, when I connect only DVI its only not working

**Comment by jocelioswarmnyc** [comment]
I have the same issue, my dvi output is not working, I got a pink screen from gpu
gpu: Afox Radeon RX550

**Comment by DmitriyyyyS** [comment]
RX 550 90% incompatible, but there are also compatible, tell me what is its ID?

**Comment by jocelioswarmnyc** [comment]
Its currently working with the fake id 0x67EF1002, I had success with two monitors, but it was using the hdmi and DP, not with DVI.

**Comment by DmitriyyyyS** [comment]
This problem is not related to this topic, there are questions to the video card itself, the issue above was about integrated graphics, but if we talk about the problem of discrete graphics in general, then this problem also exists on other RX 500 video cards, see the answers here https://github.com/acidanthera/WhateverGreen/blob/master/README.md

**Comment by jocelioswarmnyc** [comment]
great @DmitriyyyyS, thanks.

**Comment by jocelioswarmnyc** [comment]
Your folders works good for mobo **PRIME-H310M-E-BR**
